-- Travel Deal Tracker – Blog Posts
-- Run with: psql $DATABASE_URL -f supabase/migrations/0005_blog_posts.sql

create table if not exists public.blog_posts (
    id uuid primary key default gen_random_uuid(),
    slug text not null unique,
    title text not null,
    summary text not null,
    status text not null default 'published' check (status in ('draft', 'published')),
    published_at timestamptz not null default now(),
    content jsonb not null default '{}'::jsonb,
    sources jsonb not null default '[]'::jsonb,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists blog_posts_status_published_idx
    on public.blog_posts (status, published_at desc);

create index if not exists blog_posts_published_idx
    on public.blog_posts (published_at desc);

comment on table public.blog_posts is 'AI-assisted travel blog entries generated by the Blog Agent with source citations.';
